name       : sg3_utils
version    : '1.46'
release    : 5
source     :
    - https://github.com/hreinecke/sg3_utils/archive/refs/tags/v1.46.tar.gz : 6e048db9b48f78a29ad17ee948897bd6c0d71257df515a95c63e376ad8aacce9
license    :
    - GPL-2.0-or-later
    - BSD-3-Clause
component  : system.utils
summary    : Generic SCSI utilities
description: |
    The sg3_utils package contains utilities that send SCSI commands to devices. As well as devices on transports traditionally associated with SCSI (e.g. Fibre Channel (FCP), Serial Attached SCSI (SAS) and the SCSI Parallel Interface(SPI)) many other devices use SCSI command sets. ATAPI cd/dvd drives and SATA disks that connect via a translation layer or a bridge device are examples of devices that use SCSI command sets.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
